### ISSUE TITLE
 Как узнать, завершился ли поток данных ?

### ISSUE THREAD

**Issue by re1nex** [kystyn/java#22]
В связи с переездом статуса к consumer ,непонятно как узнать ,что конец потока данных .Также не ясно ,почему в случае недостатка данных мы просто прекращаем работу ,а не ждем следующую часть . Если речь идет об упрощение (размер блока у всех один), то это было сделано для проведений тестирований конвейера с разными экзекуторами как мне кажется  . К тому же  разные блоки будут в 4 работе.

**Comment by penguin-boxx** [comment]
> В связи с переездом статуса к consumer ,непонятно как узнать ,что конец потока данных .

А это нужно? Можно придумать особую логику если данных все еще не достаточно, но их уже говорят что не будет?

> К тому же разные блоки будут в 4 работе.

Когда он про это говорил? Мб сначала уточнить... Но сколько блин можно.

**Comment by penguin-boxx** [comment]
Для 4й лабы оказалось полезным, написал в ридми.
